Make AVCaptureSession calls thread safe
shogo4405/HaishinKit.swift pull request #1526
Opened 2024-07-31 22:31 UTC by levs42

## Description & motivation

This PR is a fix for #1522 to make AVCaptureSession `startRunning` and `beginConfiguration` calls thread safe.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

2024-08-02 15:19 UTC, shogo4405 requested changes
In the design of HK, the role of lockQueue is assigned to IOStream.lockQueue.
In the PR, both IOStream.lockQueue and IOCaptureSession have lockQueue, causing a redundancy in roles, which is unacceptable.
If you stop placing lockQueue in IOCaptureSession and instead use IOStream's lockQueue, it will be acceptable.

2024-08-06 20:52 UTC, levs42 commented
Updated, please take a look

2024-08-08 16:26 UTC, shogo4405 commented
## Test
**Case 1**
1. Launch Example app.
2. Launch Settings.app
    1. [Develop] -> [Reset MediaService]
3. Return Example app.

It works a camera and a microphone.

**Case 2**
https://github.com/search?q=repo%3Ashogo4405%2FHaishinKit.swift+Camera.app&type=issues
Case 1 and Case 2. It seems ok. I accepted.

2024-08-08 16:26 UTC, shogo4405 approved these changes
👍

2024-08-08 16:26 UTC, merged

2024-08-08 16:37 UTC, levs42 commented
Awesome, thank you for sharing.